language: rust
rust:
  - nightly
  - beta
  - stable

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
      export TRAVIS_CARGO_NIGHTLY_FEATURE=""

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo --only nightly test
# Benchmarks (temporarily) disabled because we’re running out of test strings.
#     travis-cargo --only nightly bench
